### ISSUE TITLE
About how to train the network? 

### ISSUE THREAD

**Issue by colincqian** [Rajhans0/Poly_INR#1]
Dear Author,
Really nice paper work! However, I am curious about the training process of the neural network. Since I notice that you are using projected discirminator, I am wondering whether you are following a GAN manner as StyleGAN-XL or following INR manner by fitting images pixel value. (GAN loss or image MSE loss) It will be really nice if you are going to release the code. Thank you again for the nice work.

**Comment by Rajhans0** [comment]
I apologize for the delay in uploading the code. The files have now been successfully uploaded to the repository.

The model is trained in a GAN setting same as StyleGAN-XL.
