### ISSUE TITLE
Access to generated images or trained models

### ISSUE THREAD

**Issue by georgestein** [Rajhans0/Poly_INR#2]
Hi there,

I am working with a group of researchers on human evaluation of generative models and we would like to include Poly-INR generated FFHQ and ImageNet images (both at 256 x 256) in our study. I see that neither models are publicly available at the moment. Are you able to provide these models, or even better 100k generated images for each model (equal class distribution for ImageNet)? 

Thanks,
George

**Comment by Rajhans0** [comment]
I apologize for the delay in uploading the code. The files have now been successfully uploaded to the repository.
I have provided the checkpoints for the ImageNet dataset. Please feel free to reach out if you encounter any issues or have any questions regarding the uploaded code.
